name: Translate de

on:
  repository_dispatch:
    types:
      - translate-de-release
  schedule:
    - cron: "47 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  translate:
    uses: ./.github/workflows/translate-locale-reusable.yml
    with:
      locale: de
      locale_slug: de
    secrets: inherit
