name: Translate id

on:
  repository_dispatch:
    types:
      - translate-id-release
  schedule:
    - cron: "47 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  translate:
    uses: ./.github/workflows/translate-locale-reusable.yml
    with:
      locale: id
      locale_slug: id
    secrets: inherit
